[phases.setup]
nixPkgs = ["wget"]

[phases.install]
cmds = ["cd ${NIXPACKS_WORKDIR} && npm install --legacy-peer-deps"]

[phases.build]
cmds = ["cd ${NIXPACKS_WORKDIR} && npm run build"]

[start]
cmd = "cd ${NIXPACKS_WORKDIR} && npm start"

[phases.setup.nixPacksBuildImage]
cmds = ["wget https://artifacts.marlin.org/oyster/binaries/oyster-cvm_latest_linux_amd64 -O /usr/local/bin/oyster-cvm && chmod +x /usr/local/bin/oyster-cvm"]
